//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country : Location
    {
        public Country()
        {
            this.Nationals = new HashSet<Individual>();
            this.PopulatedPlaces = new HashSet<PopulatedPlace>();
            this.Nationality = new SinPlurText();
        }
    
        public string Name { get; set; }
        public string Fips104 { get; set; }
        public string Iso2 { get; set; }
        public string Iso3 { get; set; }
        public Nullable<short> Ison { get; set; }
        public string Iana { get; set; }
    
        public SinPlurText Nationality { get; set; }
    
        public virtual ICollection<Individual> Nationals { get; set; }
        public virtual ICollection<PopulatedPlace> PopulatedPlaces { get; set; }
    }
}
