//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    
    public enum DateTimePrecision : byte
    {
        Second = 0,
        Minute = 1,
        Hour = 2,
        DayTime = 3,
        Day = 4,
        Week = 5,
        Month = 6,
        Season = 7,
        Year = 8,
        Decade = 9,
        Century = 10
    }
}
