//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.LocationInvolvements = new HashSet<LocationEventInvolvement>();
            this.ParticipantInvolvements = new HashSet<ParticipantEventInvolvement>();
            this.ConcludedIntervals = new HashSet<Interval>();
            this.InitializedIntervals = new HashSet<Interval>();
            this.Citations = new HashSet<Citation>();
            this.RelatedMediaItems = new HashSet<MediaItem>();
            this.Occurrence = new EventOccurrence();
        }
    
        public long Id { get; set; }
        public int TypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Importance { get; set; }
    
        public EventOccurrence Occurrence { get; set; }
    
        public virtual EventType Type { get; set; }
        public virtual ICollection<LocationEventInvolvement> LocationInvolvements { get; set; }
        public virtual ICollection<ParticipantEventInvolvement> ParticipantInvolvements { get; set; }
        public virtual ICollection<Interval> ConcludedIntervals { get; set; }
        public virtual ICollection<Interval> InitializedIntervals { get; set; }
        public virtual ICollection<Citation> Citations { get; set; }
        public virtual ICollection<MediaItem> RelatedMediaItems { get; set; }
        public virtual EventTitle Title { get; set; }
    }
}
