//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    
    public partial class EventOccurrence
    {
        public EventOccurrence()
        {
            this.Start = new ImpreciseDate();
            this.End = new ImpreciseDate();
        }
    
    
        public ImpreciseDate Start { get; set; }
        public ImpreciseDate End { get; set; }
    }
}
