//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    
    public partial class ImpreciseDate
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<DateTimePrecision> Precision { get; set; }
    }
}
