//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual : Participant
    {
        public Individual()
        {
            this.FullName = new Name();
        }
    
        public Nullable<Gender> Gender { get; set; }
        public string Profession { get; set; }
        public Nullable<long> NationalityId { get; set; }
    
        public Name FullName { get; set; }
    
        public virtual Country Nationality { get; set; }
    }
}
