//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public Interval()
        {
            this.Citations = new HashSet<Citation>();
            this.RelatedRelationships = new HashSet<Relationship>();
        }
    
        public long Id { get; set; }
        public long InitiatingEventId { get; set; }
        public long ConcludingEventId { get; set; }
        public string Description { get; set; }
    
        public virtual Event InitiatingEvent { get; set; }
        public virtual Event ConcludingEvent { get; set; }
        public virtual ICollection<Citation> Citations { get; set; }
        public virtual ICollection<Relationship> RelatedRelationships { get; set; }
    }
}
