//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationEventInvolvement
    {
        public long EventId { get; set; }
        public long LocationId { get; set; }
        public int ThematicRoleId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Location Location { get; set; }
        public virtual ThematicRole ThematicRole { get; set; }
    }
}
