//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItemType
    {
        public MediaItemType()
        {
            this.MediaItems = new HashSet<MediaItem>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<MediaItem> MediaItems { get; set; }
    }
}
