//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    
    public partial class Name
    {
        public string LastName { get; set; }
        public string GivenNames { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
    }
}
