//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization : Participant
    {
        public int TypeId { get; set; }
        public Nullable<long> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual OrganizationType Type { get; set; }
    }
}
