//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.AlternativeNames = new HashSet<AlternativeName>();
            this.EventInvolvements = new HashSet<ParticipantEventInvolvement>();
            this.DeterminantRelationships = new HashSet<Relationship>();
            this.ImmanentRelationships = new HashSet<Relationship>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        protected LocationEntityType EntityType { get; set; }
    
        public virtual ICollection<AlternativeName> AlternativeNames { get; set; }
        public virtual ICollection<ParticipantEventInvolvement> EventInvolvements { get; set; }
        public virtual ICollection<Relationship> DeterminantRelationships { get; set; }
        public virtual ICollection<Relationship> ImmanentRelationships { get; set; }
    }
}
