//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NietzscheBiography.WebSite.Infrastructure.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using NietzscheBiography.Domain.Models;
    
    public partial class NietzscheBiographyDbContext : DbContext
    {
        public NietzscheBiographyDbContext()
            : base("name=NietzscheBiographyDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlternativeName> AlternativeNames { get; set; }
        public DbSet<Citation> Citations { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventCategory> EventCategories { get; set; }
        public DbSet<LocationEventInvolvement> LocationEventInvolvements { get; set; }
        public DbSet<ParticipantEventInvolvement> ParticipantEventInvolvements { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Interval> Intervals { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MediaItem> MediaItems { get; set; }
        public DbSet<MediaItemType> MediaItemTypes { get; set; }
        public DbSet<OrganizationType> OrganizationTypes { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<Relationship> Relationships { get; set; }
        public DbSet<RelationshipCategory> RelationshipCategories { get; set; }
        public DbSet<RelationshipType> RelationshipTypes { get; set; }
        public DbSet<ThematicRole> ThematicRoles { get; set; }
    }
}
